# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

VAGRANTFILE_API_VERSION = '2'.freeze

# Read YAML file with box details
servers = YAML.load_file('servers.yaml')

# Variables
box            = 'bento/centos-7.5'  # 'bento/oracle-6.9'

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  servers.each do |name, server|
  
    non_rotational = server['non_rotational']
    u01_disk       = server['u01_disk']
    inv_disk       = server['inv_disk']
    diag_disk      = server['diag_disk']
    ram_size       = server['ram']
    cpu_count      = server['cpu']
  #  data_disk          = server['data_disk']
  #  fra_disk           = server['fra_disk']
  #  ctl_disk1          = server['ctllog1']
  #  ctl_disk2          = server['ctllog2']
    
    config.vm.box = box

    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.network "forwarded_port", guest: 8443, host: 8443
    config.vm.network "forwarded_port", guest: 1521, host: 1521
    config.vm.network "forwarded_port", guest: 5500, host: 5500

    config.vm.provider "virtualbox" do |vb|
      vb.memory = ram_size
      vb.cpus   = cpu_count
      vb.name   = name

      vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', '0', '--nonrotational', non_rotational]

      unless File.exist?(u01_disk)
        vb.customize ['createhd', '--filename', u01_disk, '--size', 100 * 1024]
      end
      vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', u01_disk, '--nonrotational', var_non_rotational]

      unless File.exist?(inv_disk)
        vb.customize ['createhd', '--filename', inv_disk, '--size', 10 * 1024]
      end
      vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', inv_disk, '--nonrotational', var_non_rotational]

      unless File.exist?(diag_disk)
        vb.customize ['createhd', '--filename', diag_disk, '--size', 100 * 1024]
      end
      vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 3, '--device', 0, '--type', 'hdd', '--medium', diag_disk, '--nonrotational', var_non_rotational]

     end

    config.vm.provision "shell", inline: <<-SHELL
      sh /vagrant/scripts/setup.sh
    SHELL
    
  end