# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

VAGRANTFILE_API_VERSION = '2'.freeze

# Read YAML file with box details
servers = YAML.load_file('servers.yaml')

# Variables
box            = 'bento/centos-7.5'  # 'bento/oracle-6.9'
#vm_name        = 'xe.lab.local'


# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  servers.each do |name, server|
  
    non_rotational = server['non_rotational']
    cpus           = server['cpucount']
    mem_size       = server['ram']
    
    config.vm.box = box

    #apex
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.network "forwarded_port", guest: 8081, host: 8081
    # db
    config.vm.network "forwarded_port", guest: 1521, host: 1521
    # em
    config.vm.network "forwarded_port", guest: 5500, host: 5500
    config.vm.network "forwarded_port", guest: 5501, host: 5501
    # tomcat
    config.vm.network "forwarded_port", guest: 8443, host: 8443
    config.vm.network "private_network", ip: '192.168.56.10' 

    config.vm.provider "virtualbox" do |vb|
      vb.memory = mem_size
      vb.cpus   = cpus
      vb.name   = server['name']

    end

    config.vm.provision "shell", inline: <<-SHELL
      sh /vagrant/scripts/setup.sh
    SHELL

  end
    
end